#!/bin/sh

set -e
set -x

app_id=`basename $PWD`

if test -f $app_id.json ; then
   manifest=$app_id.json
elif test -f $app_id.yaml; then
   manifest=$app_id.yaml
elif test -f $app_id.yml; then
   manifest=$app_id.yml
else
   echo "Manifest not found"
   exit 1
fi

app_name=`echo $app_id | grep -o "[^\\.]*$"`

git checkout branch/21.08
git pull -r origin branch/21.08
git checkout -b branch/22.08

sed -i 's/runtime-version": "21\.08/runtime-version": "stable/' $app_id.*
sed -i 's/21\.08/22\.08/' $app_id.*
sed -i 's/22\.08beta/22\.08/' $app_id.*
sed -i '/ln -sf vst/d' $app_id.*
sed -i '/linux-audio\/jack2.json/d' $app_id.*

git add $app_id.*
git commit -m "22.08 branch"
fp-build

