#!/bin/sh

set -e
set -x

app_id=`basename $PWD`

if test -f $app_id.json ; then
   manifest=$app_id.json
elif test -f $app_id.yaml; then
   manifest=$app_id.yaml
elif test -f $app_id.yml; then
   manifest=$app_id.yml
else
   echo "Manifest not found"
   exit 1
fi

app_name=`echo $app_id | grep -o "[^\\.]*$"`

git checkout branch/22.08
git pull -r origin branch/22.08
git checkout -b branch/23.08

sed -i 's/22\.08/23\.08/' $app_id.*
sed -i 's/23\.08beta/23\.08/' $app_id.*

git add $app_id.*
git commit -m "23.08 branch"
git submodule update --init
fp-build

