#!/bin/sh

set -e
set -x

app_id=`basename $PWD`

if test -f $app_id.json ; then
   manifest=$app_id.json
elif test -f $app_id.yaml; then
   manifest=$app_id.yaml
elif test -f $app_id.yml; then
   manifest=$app_id.yml
else
   echo "Manifest not found"
   exit 1
fi

app_name=`echo $app_id | grep -o "[^\\.]*$"`

git checkout branch/20.08
git pull -r origin branch/20.08
git checkout -b branch/21.08

sed -i 's/20\.08/21\.08/' $app_id.*
sed -i 's/21\.08beta/21\.08/' $app_id.*

git add $app_id.*
git commit -m "21.08 branch"
fp-build

