#!/bin/sh

# fail on the first error.
set -e

if [ -z "$FLATPAK_BUILDER" ] ; then
   if which flatpak-builder ; then
      FLATPAK_BUILDER=flatpak-builder
   else
      FLATPAK_BUILDER="flatpak run org.flatpak.Builder"
   fi
fi

echo "Using $FLATPAK_BUILDER to build"

app_id=`basename $PWD`

if test -f $app_id.json ; then
   manifest=$app_id.json
elif test -f $app_id.yaml; then
   manifest=$app_id.yaml
elif test -f $app_id.yml; then
   manifest=$app_id.yml
else
   echo "Manifest not found"
   exit 1
fi



if test -z "$NO_INSTALL" ; then
   $FLATPAK_BUILDER --force-clean --ccache --install --user $* repo $manifest
else
   $FLAPTAK_BUILDER --force-clean --ccache $* repo $manifest
fi

# Newer version of flatpak-builder seems to have the AppStream file in metainfo.
appstream_file=repo/files/share/metainfo/$app_id.metainfo.xml
if test ! -f $appstream_file; then
    appstream_file=repo/files/share/appdata/$app_id.appdata.xml
fi

flatpak run org.freedesktop.appstream-glib validate $appstream_file
flatpak run --command=appstreamcli org.flatpak.Builder validate $appstream_file

flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest $manifest
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions builddir repo

flatpak run org.flathub.flatpak-external-data-checker $manifest
fp-nobackup repo
fp-nobackup .flatpak-builder
