#!/bin/sh

branch="24.08"
plugins=

for i in `cat data/audio-plugins-list`; do
    if [[ "$i" =~ ^org.freedesktop.LinuxAudio.Plugins ]] ;then
        plugins="${plugins} ${i}//${branch}"
    fi
done

flatpak install $plugins
